import { XecutorError } from "./service.js";

export const MCP_PROTOCOL_VERSION = "2025-06-18";
export const MCP_SERVER_INFO = { name: "the-xecutor", version: "0.1.0" };

export const XECUTOR_TOOLS = [
  {
    name: "propose_order",
    description: "Submit one immutable Bench execution handoff to Adam's approval inbox. This never places a broker order. No fields are inferred.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        client_submission_id: { type: "string", minLength: 1, maxLength: 128, description: "Stable idempotency key generated by this bot." },
        handoff: { type: "object", description: "Complete bench-execution-handoff-v1 object. Unknown fields refuse." },
      },
      required: ["client_submission_id", "handoff"],
    },
  },
  {
    name: "get_order_status",
    description: "Read the status of this bot's previously submitted proposal. Returns simulation state only; Stage 1 has no live broker route.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { proposal_id: { type: "string", pattern: "^XEC-[A-F0-9]{16}$" } },
      required: ["proposal_id"],
    },
  },
  {
    name: "withdraw_proposal",
    description: "Withdraw this bot's proposal while it is still awaiting Adam's approval. A terminal proposal cannot be revived.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        proposal_id: { type: "string", pattern: "^XEC-[A-F0-9]{16}$" },
        reason: { type: "string", maxLength: 240 },
      },
      required: ["proposal_id"],
    },
  },
];

function toolResult(value, isError = false) {
  return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], isError };
}

export async function runTool(service, sourceClient, name, args = {}) {
  if (name === "propose_order") {
    return service.createProposal({ sourceClient, clientSubmissionId: args.client_submission_id, handoff: args.handoff });
  }
  if (name === "get_order_status") {
    return service.getProposal(args.proposal_id, { sourceClient, includeConfirmation: false });
  }
  if (name === "withdraw_proposal") {
    return service.withdraw(args.proposal_id, { sourceClient, reason: args.reason });
  }
  throw new XecutorError("TOOL_NOT_FOUND", `unknown tool: ${name}`, 404);
}

export async function handleMcpMessage(service, sourceClient, message) {
  if (!message || message.jsonrpc !== "2.0") {
    return { jsonrpc: "2.0", id: message?.id ?? null, error: { code: -32600, message: "invalid JSON-RPC request" } };
  }
  const { id, method, params } = message;
  if (method === "notifications/initialized" || method === "notifications/cancelled") return null;
  if (method === "initialize") {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        protocolVersion: params?.protocolVersion || MCP_PROTOCOL_VERSION,
        capabilities: { tools: { listChanged: false } },
        serverInfo: MCP_SERVER_INFO,
        instructions: "The Xecutor Stage 1 accepts immutable order proposals for Adam. It cannot approve or place a live broker order.",
      },
    };
  }
  if (method === "ping") return { jsonrpc: "2.0", id, result: {} };
  if (method === "tools/list") return { jsonrpc: "2.0", id, result: { tools: XECUTOR_TOOLS } };
  if (method === "tools/call") {
    try {
      const value = await runTool(service, sourceClient, params?.name, params?.arguments || {});
      return { jsonrpc: "2.0", id, result: toolResult(value) };
    } catch (error) {
      const body = { ok: false, code: error.code || "TOOL_ERROR", error: error.message || "tool failed" };
      return { jsonrpc: "2.0", id, result: toolResult(body, true) };
    }
  }
  return { jsonrpc: "2.0", id, error: { code: -32601, message: `method not found: ${method}` } };
}
